name: Sync GitLab Contributions

on:
  # 毎日日本時間の午前9時に自動実行 (UTCの0時)
  schedule:
    - cron: '0 0 * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      #    ※ ツールがGitリポジトリに書き込むために必要です
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js環境をセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 同期ツールをインストール (★ここを修正)
      - name: Install gitlab2github
        run: npm install -g gitlab2github

      # 4. 同期を実行 (★ここを修正)
      - name: Run sync
        # Secretsから情報を取得し、ツールの引数として渡します
        run: >
          gitlab2github
          --gitlab-url=${{ secrets.GITLAB_URL }}
          --gitlab-token=${{ secrets.GITLAB_TOKEN }}
          --gitlab-username=${{ secrets.GITLAB_USERNAME }}
          --github-token=${{ secrets.GH_PAT }}
          --github-repository=${{ github.repository }}
        env:
          # コミットを行うボットのユーザー情報を設定
          GIT_AUTHOR_NAME: 'GitLab Sync Bot'
          GIT_AUTHOR_EMAIL: 'bot@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'GitLab Sync Bot'
          GIT_COMMITTER_EMAIL: 'bot@users.noreply.github.com'
