name: Sync GitLab Contributions

on:
  # 毎日日本時間の午前9時に自動実行 (UTCの0時)
  schedule:
    - cron: '0 0 * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. アクションがこのリポジトリにコミットするために、まずチェックアウトします
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. GitLab 同期アクションを実行 (★ここを全面的に修正)
      - name: Sync GitLab Contributions
        uses: k-p-d/sync-gitlab-contributions@v1 # <- これが正しいアクションです
        with:
          # "Secrets"に登録した情報を渡します
          gitlab-url: ${{ secrets.GITLAB_URL }}
          gitlab-username: ${{ secrets.GITLAB_USERNAME }}
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          
          github-token: ${{ secrets.GH_PAT }}
          github-repository: ${{ github.repository }} # このリポジトリを指定
