name: Sync GitLab Contributions

on:
  # 毎日日本時間の午前9時に自動実行 (UTCの0時)
  schedule:
    - cron: '0 0 * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      #    ※ このアクションがコミットをプッシュするために必要です
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. GitLab 同期アクションを実行 (★ここを全面的に変更)
      - name: Sync GitLab Contributions
        uses: comPoota/gitlab-contribution-sync@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_username: ${{ secrets.GITLAB_USERNAME }}
