name: Sync GitLab Contributions

on:
  # 毎日日本時間の午前9時に自動実行 (UTCの0時)
  schedule:
    - cron: '0 0 * * *'
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      #    ※ このアクションがコミット履歴を読み書きするために必要です
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 履歴全体をフェッチします（同期に必要）
          fetch-depth: 0

      # 2. GitLab 同期アクションを実行 (★ここを全面的に修正)
      - name: Sync GitLab Contributions
        uses: gowee/sync-contrib-calendar-action@v1 # <- これが現在動作するアクションです
        with:
          # "Secrets"に登録した情報を渡します
          github_token: ${{ secrets.GH_PAT }}
          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
          gitlab_url: ${{ secrets.GITLAB_URL }}
          gitlab_username: ${{ secrets.GITLAB_USERNAME }}
          
          # どのサービスから同期するかを指定します
          source: 'gitlab'
